version: '3.7'

networks:
  frontend:
    external: true

services:

  db:
    image: mysql:5.7
    restart: unless-stopped
    volumes:
      - ./wp-data:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: wordpress
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    # ports:
    #   - 8889:3306
    networks:
      frontend:
        ipv4_address: 10.5.0.11

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    # ports:
    #   - 3001:80
    networks:
      frontend:
        ipv4_address: 10.5.0.12

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: unless-stopped
    # ports:
    #   - 8888:80
    #   - 443:443
    environment:
       WORDPRESS_DB_HOST: db
       WORDPRESS_DB_USER: ${MYSQL_USER}
       WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./wordpress-files:/var/www/html
    container_name: wordpress-site
    networks:
      frontend:
        ipv4_address: 10.5.0.15