version: "2"

networks:
    frontend:
        external: true

services: 
    surfshark:
        image: ilteoood/docker-surfshark
        container_name: surfshark
        environment: 
            - SURFSHARK_USER=d6Pgb5rsXzXh6atV8CcbsHek
            - SURFSHARK_PASSWORD=gnr47WTfQRYfwHY5CYsVsQYg
            - SURFSHARK_COUNTRY=it
            - SURFSHARK_CITY=mil
            - CONNECTION_TYPE=udp
            - LAN_NETWORK=
        cap_add: 
            - NET_ADMIN
        devices:
            - /dev/net/tun
        # ports:
        #     - 9091:9091 #we open here the port for transmission, as this container will be the access point for the others
        restart: unless-stopped
        dns:
            - 1.1.1.1
        networks:
            - frontend
    # service_test:
    #     image: byrnedo/alpine-curl
    #     container_name: alpine
    #     command: -L 'https://ipinfo.io'
    #     depends_on: 
    #         - surfshark
    #     network_mode: service:surfshark
    #     restart: always
    # transmission:
    #     image: linuxserver/transmission
    #     container_name: transmission
    #     environment:
    #         - PUID=1000
    #         - PGID=1000
    #         - TZ=Europe/Rome
    #     # ports:
    #     #     - 9091:9091 #needed to access transmission's GUI
    #     network_mode: service:surfshark
    #     restart: unless-stopped